/* Exercise book navigation, the animation lifecycle, and the unenhanced document. */
const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const root = require('node:path').resolve(__dirname, '..');
const html = fs.readFileSync(root+'/docs/index.html','utf8');
const script = fs.readFileSync(root+'/static/js/storybook.js','utf8');
const wait = () => new Promise(resolve => setImmediate(resolve));
function setup({reduced=true,narrow=false,hash=''}={}) {
 const dom = new JSDOM(html,{url:'https://tartary.innerversepodcast.com/'+hash,runScripts:'outside-only',pretendToBeVisual:true});
 const w=dom.window,d=w.document,animations=[];
 w.matchMedia=query=>({matches:query.includes('reduced-motion')?reduced:narrow});
 w.Element.prototype.scrollIntoView=function(){};
 w.Element.prototype.animate=function(frames,options){let resolve;const a={frames,options,finished:new Promise(r=>{resolve=r}),cancel(){},finish(){resolve()}};animations.push(a);return a};
 return {dom,w,d,animations,run:()=>w.eval(script)};
}
(async()=>{
 let {dom,w,d,run}=setup();
 assert.equal(d.querySelectorAll('.story-chapter:not([hidden])').length,8);
 assert.equal(d.querySelectorAll('.story-inscription').length,8);
 for(const img of d.querySelectorAll('.story-illumination img')) assert.ok(fs.existsSync(root+'/docs/'+img.getAttribute('src')));
 console.log('PASS no-script book contains every illustration, chapter, and feature link');
 run();
 assert.equal(d.querySelectorAll('.story-chapter:not([hidden])').length,1);
 assert.equal(d.querySelector('[data-book-prev]').disabled,true);
 d.querySelector('[data-book-next]').click();
 assert.equal(w.location.hash,'#chapter-words');
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-words');
 d.querySelector('[data-book-tab="4"]').click();
 assert.equal(d.querySelector('.story-inscription[href="./dial/"]').closest('section').hidden,false);
 d.querySelector('[data-book-tab="4"]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'End',bubbles:true}));
 assert.equal(d.querySelector('[data-book-next]').disabled,true);
 d.querySelector('[data-book-prev]').click();
 assert.equal(w.location.hash,'#chapter-places');
 d.querySelector('[data-book-home]').click();
 assert.equal(w.location.hash,'#chapter-opening');
 w.history.replaceState(null,'','#chapter-journeys');w.dispatchEvent(new w.PopStateEvent('popstate'));
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-journeys');
 console.log('PASS reduced-motion page turns, side tabs, keyboard limits, home, and history');dom.window.close();
 let env=setup({reduced:false,hash:'#chapter-maps'});({dom,w,d,run}=env);run();
 d.querySelector('[data-book-next]').click();
 assert.equal(env.animations.length,1);assert.equal(d.querySelector('.story-turner').hidden,false);
 assert.equal(d.querySelector('.story-turner-front .story-title').textContent,'The painted world');
 assert.equal(d.querySelector('.story-turner-back img').getAttribute('src'),'./assets/storybook/journeys.webp');
 assert.ok(+d.querySelector('#chapter-journeys').style.zIndex > +d.querySelector('#chapter-maps').style.zIndex);
 assert.equal(new Set([...d.querySelectorAll('[id]')].map(n=>n.id)).size,d.querySelectorAll('[id]').length);
 env.animations[0].finish();await wait();
 assert.equal(d.querySelector('.story-turner').hidden,true);
 assert.equal(d.querySelectorAll('.story-chapter:not([hidden])').length,1);
 d.querySelector('[data-book-prev]').click();
 assert.equal(d.querySelector('.story-turner-front .story-title').textContent,'The painted world');
 assert.equal(d.querySelector('.story-turner-back img').getAttribute('src'),'./assets/storybook/journeys.webp');
 const revealed=d.querySelector('#chapter-maps'), departing=d.querySelector('#chapter-journeys');
 assert.ok(+revealed.style.zIndex > +departing.style.zIndex,'reverse turn reveals the earlier chapter above the later DOM sibling');
 assert.equal(revealed.querySelector('.story-page-art').style.visibility,'');
 assert.equal(revealed.querySelector('.story-page-text').style.visibility,'hidden');
 assert.equal(d.querySelector('.story-tab[aria-current="page"]').getAttribute('aria-controls'),'chapter-maps');
 env.animations[1].finish();await wait();
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-maps');
 assert.ok([...d.querySelectorAll('.story-chapter')].every(c=>c.style.zIndex===''&&c.style.position===''));
 d.querySelector('[data-book-next]').click();
 w.history.replaceState(null,'','#chapter-opening');w.dispatchEvent(new w.PopStateEvent('popstate'));
 env.animations[2].finish();await wait();env.animations[3].finish();await wait();
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-opening');
 console.log('PASS forward/back leaf faces, reverse-turn reveal order, active bookmark, cleanup, unique IDs, and navigation during a turn');dom.window.close();
 env=setup({reduced:false,narrow:true});({dom,w,d,run}=env);run();
 const book=d.querySelector('[data-storybook]');
 let start=new w.Event('touchstart',{bubbles:true});Object.defineProperty(start,'touches',{value:[{clientX:250,clientY:150}]});book.dispatchEvent(start);
 let end=new w.Event('touchend',{bubbles:true});Object.defineProperty(end,'changedTouches',{value:[{clientX:100,clientY:155}]});book.dispatchEvent(end);
 assert.equal(w.location.hash,'#chapter-words');env.animations[0].finish();await wait();
 assert.equal(d.querySelectorAll('.story-chapter:not([hidden])').length,1);
 console.log('PASS mobile swipe and narrow-layout transition');dom.window.close();
 env=setup({reduced:false});({dom,w,d,run}=env);run();
 let release;d.querySelector('#chapter-words img').decode=()=>new Promise(r=>{release=r});
 d.querySelector('[data-book-next]').click();assert.equal(env.animations.length,0);
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-opening');
 release();await wait();assert.equal(env.animations.length,1);env.animations[0].finish();await wait();
 assert.equal(d.querySelector('.story-chapter:not([hidden])').id,'chapter-words');
 assert.equal(d.querySelector('[data-storybook]').hasAttribute('aria-busy'),false);
 console.log('PASS a cold illustration loads before its leaf is turned');dom.window.close();
 console.log('ALL STORYBOOK CHECKS PASS');
})().catch(e=>{console.error(e);process.exit(1)});
